site_name: Patrones de Diseño (MOOC)
site_description: Curso abierto de patrones de diseño para ingeniería de software
repo_url: https://github.com/tectijuana/pdd
theme:
name: material
features:
- navigation.sections
- navigation.top
- content.action.edit
- search.highlight
- toc.integrate
nav:
- Inicio: index.md
- Programa: syllabus.md
- Guía docente: guia_docente.md
- Metodología: metodologia.md
- Bibliografía: bibliografia.md
markdown_extensions:
- admonition
- toc:
permalink: true
- codehilite
plugins:
- search
